version: '3'
volumes:
  pgdata:
services:
  messenger:
    build: ./db
    container_name: messenger
    command: -c 'listen_addresses="*"'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=messenger_db
    restart: on-failure
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - messenger

networks:
  messenger:
